name = "JLisp"
uuid = "0f8f2862-4eb6-11e9-3073-85d0a5bdff0d"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
